// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/facebook/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/facebook/callback.get').default>>>>
    }
    '/api/auth/facebook': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/facebook/index.get').default>>>>
    }
    '/api/auth/forgot-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/forgot-password.post').default>>>>
    }
    '/api/auth/google/callback': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/google/callback.get').default>>>>
    }
    '/api/auth/google': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/google/index.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/auth/reset-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/reset-password.post').default>>>>
    }
    '/api/feedback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feedback.post').default>>>>
    }
    '/api/feedbacks': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/feedbacks.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}